import "../globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

// import { AppSidebar } from '@/components/app-sidebar';
import Footer from "@/components/navigation/footer/footer";
import TopNavigation from "@/components/navigation/top_navigation/top-navigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={"grid grid-cols-1 antialiased"}>
				<TopNavigation />
				<main
					role="main"
					className="flex w-full flex-col items-start justify-start xl:container xl:mx-auto"
				>
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}

//
// {/*<SidebarProvider className={'rounded-[30px] overflow-hidden'}>*/}
// {/*	<AppSidebar />*/}
// {/*	<SidebarInset className={'bg-[#b3eabc] rounded-[30px] overflow-hidden'}>*/}
// {/*		<main className={'rounded-[30px] overflow-hidden'}>*/}
// {/*			<SidebarTrigger />*/}
// {/*			{children}*/}
//
// {/*			/!*<AppSidebar />*!/*/}
// {/*		</main>*/}
// {/*	</SidebarInset>*/}
// {/*</SidebarProvider>*/}
