import "@/app/globals.css";

import type { Metadata } from "next";

import { AuthenticatedLayout } from "@/components/wrappers/loaders/authenticated-layout";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={"grid grid-cols-1 antialiased"}>
				<AuthenticatedLayout>{children}</AuthenticatedLayout>
			</body>
		</html>
	);
}
