import "@/app/globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={
					"flex h-screen flex-col items-center justify-center antialiased"
				}
			>
				<main className={"overflow-hidden rounded-[30px]"}>
					{children}
					<Toaster />
				</main>
			</body>
		</html>
	);
}
