export interface PrivacySection {
	title: string;
	content: string[];
}

export const privacyData = {
	title: "Privacy Policy",
	lastUpdated: "March 4, 2024",
	introduction:
		"At Push to Post, accessible at commit.jolexhive.com, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service.",
	sections: [
		{
			title: "1. Information We Collect",
			content: [
				"We collect information that you provide directly to us when you register for an account, create or modify your profile, or interact with our service.",
				"This includes your name, email address, LinkedIn profile information, and any other information you choose to provide.",
				"We also collect information about your use of our service, including generated posts and interactions with our platform.",
				"We do not store your GitHub commits or use your data to train our AI models. Instead, users generate a webhook URL from our service, which they can integrate with their GitHub repositories.",
			],
		},
		{
			title: "2. GitHub and LinkedIn Integration",
			content: [
				"To provide our service, we require access to your LinkedIn account.",
				"We only access the information that you explicitly authorize.",
				"For GitHub, we provide a webhook URL that you can integrate with your GitHub repositories. We do not directly connect to your GitHub account.",
				"We use this access to analyze your commits in real time (without storing them) and generate appropriate posts based on your development activity.",
			],
		},
		{
			title: "3. How We Use Your Information",
			content: [
				"We use the information we collect to provide, maintain, and improve our services.",
				"This includes analyzing your GitHub commits in real time (without storing them) to generate posts, personalizing your experience, and communicating with you about your account and our services.",
				"We store only the posts generated by our AI to help you manage your content and improve our service.",
			],
		},
		{
			title: "4. AI Processing and Data Handling",
			content: [
				"Our service uses artificial intelligence to analyze your GitHub commits and generate posts.",
				"We do not store your GitHub commit data or use it to train our AI models.",
				"The generated posts are stored on our platform to help you manage your content and improve our service.",
			],
		},
		{
			title: "5. Data Retention",
			content: [
				"We retain your account information and generated posts for as long as your account is active or as needed to provide you with our services.",
				"If you wish to request data deletion or unlink your LinkedIn account, please contact us directly at brilliant@jolexhive.com.",
			],
		},
		{
			title: "6. Data Security",
			content: [
				"We implement technical and organizational measures to protect your personal information.",
				"However, no method of transmission over the Internet or electronic storage is completely secure, and we cannot guarantee absolute security.",
			],
		},
		{
			title: "7. Sharing Your Information",
			content: [
				"We do not sell your personal information to third parties.",
				"We may share your information with third-party service providers who perform services on our behalf, such as hosting, data analysis, and customer service.",
				"These service providers are only permitted to use your information for the purposes of providing services to us.",
			],
		},
		{
			title: "8. Your Rights and Choices",
			content: [
				"While our platform currently does not provide direct options to delete your account or revoke your LinkedIn integration, you can contact us at brilliant@jolexhive.com to request these actions.",
				"You may also have additional rights under applicable data protection laws, such as the right to access, correct, or delete your personal information.",
			],
		},
		{
			title: "9. Cookies and Tracking Technologies",
			content: [
				"We use cookies and similar tracking technologies to track activity on our service and hold certain information.",
				"You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.",
				"However, if you do not accept cookies, you may not be able to use some portions of our service.",
			],
		},
		{
			title: "10. Children's Privacy",
			content: [
				"Our service is not directed to children under the age of 13, and we do not knowingly collect personal information from children under 13.",
				"If we learn that we have collected personal information from a child under 13, we will take steps to delete that information as quickly as possible.",
			],
		},
		{
			title: "11. International Data Transfers",
			content: [
				"Your information may be transferred to and maintained on computers located outside of your state, province, or country.",
				"If you are located outside the United States and choose to provide information to us, please note that we transfer the data to the United States and process it there.",
				"Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.",
			],
		},
		{
			title: "12. Changes to This Privacy Policy",
			content: [
				"We may update our Privacy Policy from time to time.",
				"We will notify you of any changes by posting the new Privacy Policy on this page and updating the 'Last Updated' date.",
				"You are advised to review this Privacy Policy periodically for any changes.",
			],
		},
		{
			title: "13. Contact Us",
			content: [
				"If you have any questions about this Privacy Policy or wish to request account deletion or revoke LinkedIn access, please contact us at brilliant@jolexhive.com.",
			],
		},
	],
};
