export interface PrivacySection {
	title: string;
	content: string[];
}

export const privacyData = {
	title: "Privacy Policy",
	lastUpdated: "May 10, 2025",
	introduction:
		"At Push to Post, accessible at commit.jolexhive.com, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service. Push to Post utilizes Paddle as a Merchant of Record for payment processing, but remains an independent service with its own data practices and intellectual property.",
	sections: [
		{
			title: "1. Information We Collect",
			content: [
				"We collect information that you provide directly to us when you register for an account, create or modify your profile, or interact with our service.",
				"This includes your name, email address, LinkedIn profile information, and any other information you choose to provide.",
				"We also collect information about your use of our service, including generated posts and interactions with our platform.",
				"We do not store your GitHub commits or use your data to train our AI models. Instead, users generate a webhook URL from our service, which they can integrate with their GitHub repositories.",
			],
		},
		{
			title: "2. Categories of Personal Data",
			content: [
				"Personal details: name, preferred name.",
				"Contact details: email address, LinkedIn profile information.",
				"Service usage data: information about how you interact with our platform, generated posts, settings preferences.",
				"Payment information: when you subscribe to our service, our payment processor (Paddle) will collect necessary billing information.",
				"Device information: IP address, browser type, operating system, and other technical information when you access our service.",
			],
		},
		{
			title: "3. Legal Basis for Processing",
			content: [
				"We process your personal data based on the following legal grounds:",
				"Performance of Contract: Processing necessary to provide you with our service according to our Terms of Use.",
				"Legitimate Interests: We may process data based on our legitimate interests in operating, improving, and securing our service, as long as these interests are not overridden by your rights.",
				"Consent: Where required by law, we process data based on your explicit consent, which you may withdraw at any time.",
				"Legal Obligation: We may process data to comply with applicable laws and regulations.",
			],
		},
		{
			title: "4. GitHub and LinkedIn Integration",
			content: [
				"To provide our service, we require access to your LinkedIn account.",
				"We only access the information that you explicitly authorize.",
				"For GitHub, we provide a webhook URL that you can integrate with your GitHub repositories. We do not directly connect to your GitHub account.",
				"We use this access to analyze your commits in real time (without storing them) and generate appropriate posts based on your development activity.",
			],
		},
		{
			title: "5. How We Use Your Information",
			content: [
				"We use the information we collect to provide, maintain, and improve our services.",
				"This includes analyzing your GitHub commits in real time (without storing them) to generate posts, personalizing your experience, and communicating with you about your account and our services.",
				"We store only the posts generated by our AI to help you manage your content and improve our service.",
				"We may use your contact information to send service-related communications.",
			],
		},
		{
			title: "6. AI Processing and Data Handling",
			content: [
				"Our service uses artificial intelligence to analyze your GitHub commits and generate posts.",
				"We do not store your GitHub commit data or use it to train our AI models.",
				"The generated posts are stored on our platform to help you manage your content and improve our service.",
			],
		},
		{
			title: "7. Data Retention",
			content: [
				"We retain your account information and generated posts for as long as your account is active or as needed to provide you with our services.",
				"We apply the following retention criteria:",
				"- Account information is retained as long as you maintain an active account with us.",
				"- Generated posts are retained until you delete them or your account.",
				"- Usage data is retained for a period necessary for our analytics and service improvement purposes, typically not exceeding 24 months.",
				"If you wish to request data deletion or unlink your LinkedIn account, please contact us directly at brilliant@jolexhive.com.",
			],
		},
		{
			title: "8. Data Security",
			content: [
				"We implement appropriate technical and organizational security measures to protect your personal information against accidental or unlawful destruction, loss, alteration, unauthorized disclosure, or access.",
				"These measures include data encryption, access controls, regular security assessments, and employee training on data protection.",
				"However, no method of transmission over the Internet or electronic storage is completely secure, and we cannot guarantee absolute security.",
			],
		},
		{
			title: "9. Sharing Your Information",
			content: [
				"We do not sell your personal information to third parties.",
				"We may share your information with:",
				"- Third-party service providers who perform services on our behalf, such as hosting, data analysis, payment processing (Paddle), and customer service.",
				"- Legal authorities when required by law, to protect our rights, or in response to a legal process.",
				"These service providers are only permitted to use your information for the purposes of providing services to us and are bound by contractual obligations to keep personal information confidential and secure.",
			],
		},
		{
			title: "10. International Data Transfers",
			content: [
				"Your information may be transferred to and maintained on computers located outside of your state, province, or country.",
				"If you are located outside the United States and choose to provide information to us, please note that we transfer the data to the United States and process it there.",
				"For transfers from the UK/EEA to countries not deemed to provide adequate protection, we implement appropriate safeguards such as Standard Contractual Clauses approved by the European Commission or UK authorities.",
				"Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.",
			],
		},
		{
			title: "11. Your Rights and Choices",
			content: [
				"Depending on your location, you may have certain rights regarding your personal data:",
				"- Right to access and obtain a copy of your personal data",
				"- Right to rectification of inaccurate personal data",
				"- Right to erasure ('right to be forgotten')",
				"- Right to restrict processing",
				"- Right to data portability",
				"- Right to object to processing",
				"- Right to withdraw consent at any time",
				"- Right to lodge a complaint with a supervisory authority",
				"While our platform currently does not provide direct options to delete your account or revoke your LinkedIn integration, you can contact us at brilliant@jolexhive.com to exercise these rights.",
			],
		},
		{
			title: "12. Cookies and Tracking Technologies",
			content: [
				"We use cookies and similar tracking technologies to track activity on our service and hold certain information.",
				"These technologies help us analyze usage patterns, remember your preferences, and improve user experience.",
				"You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.",
				"However, if you do not accept cookies, you may not be able to use some portions of our service.",
			],
		},
		{
			title: "13. Children's Privacy",
			content: [
				"Our service is not directed to children under the age of 13, and we do not knowingly collect personal information from children under 13.",
				"If we learn that we have collected personal information from a child under 13, we will take steps to delete that information as quickly as possible.",
			],
		},
		{
			title: "14. California Resident Rights",
			content: [
				"If you are a California resident, you have rights under the California Consumer Privacy Act (CCPA) regarding your personal information, including:",
				"- The right to know what personal information is collected, used, shared, or sold",
				"- The right to delete personal information held by businesses",
				"- The right to opt-out of the sale of personal information",
				"- The right to non-discrimination for exercising CCPA rights",
				"We do not sell personal information as defined by the CCPA.",
			],
		},
		{
			title: "15. Changes to This Privacy Policy",
			content: [
				"We may update our Privacy Policy from time to time.",
				"We will notify you of any changes by posting the new Privacy Policy on this page and updating the 'Last Updated' date.",
				"You are advised to review this Privacy Policy periodically for any changes.",
				"Changes become effective when posted on this page.",
			],
		},
		{
			title: "16. Intellectual Property and Service Independence",
			content: [
				"This Privacy Policy does not grant any rights to Push to Post's intellectual property, including but not limited to our name, trademark, service features, business model, or technology to any third parties, including payment processors.",
				"Push to Post remains an independent service provider maintaining exclusive ownership and control over its systems, features, and technology.",
				"Our use of third-party services, including payment processing through Paddle, does not create any partnership, joint venture, agency, franchise, or employee relationship, nor does it transfer any ownership or access rights to our systems beyond what is strictly necessary for the provision of specific contracted services.",
			],
		},
		{
			title: "17. Contact Us",
			content: [
				"If you have any questions about this Privacy Policy or wish to exercise any of your rights, please contact us at brilliant@jolexhive.com.",
				"Data Controller: JolexHive, brilliant@jolexhive.com",
			],
		},
	],
};
