/* eslint-disable import/no-unresolved */
import "@/app/globals.css";

import type { Metadata } from "next";
import { Suspense } from "react";

import { Toaster } from "@/components/ui/sonner";
import WorkspaceTopNav from "@/components/workspace/nav";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={"bg-[#f4f4f4] antialiased"}>
				<Suspense>
					<WorkspaceTopNav />
					<main
						role="main"
						className="relative flex w-full flex-col items-start justify-start xl:container xl:mx-auto"
					>
						{children}
						<Toaster />
					</main>
				</Suspense>
			</body>
		</html>
	);
}
